<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="urn:org.nasdanika.architecture.core" nsPrefix="org.nasdanika.architecture.core">
  <eAnnotations source="urn:org.nasdanika">
    <details key="documentation-reference" value="doc/package-summary.md"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" interface="true"
      eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//NamedElement ../../org.nasdanika.ncore/model/ncore.ecore#//Documented">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element ID to use as EKey - a unique identifier of this element among its siblings in the parent's containment reference. "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//Temporal #//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A named document temporal with ID."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Facet" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A marker interface for classes which can be used as architecture element facets"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureElement" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//Period #//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An element of an architecture model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true" eKeys="#//ModelElement/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Events associated with this architecture element. Events can be used as bases for temporals and periods, e.g. other architecture elements or increments."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="increments" upperBound="-1"
        eType="#//Increment" containment="true" eKeys="#//ModelElement/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Architecture element increments. E.g. releases/versions for a technology product or lifecycle for a technology product release. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
        eType="#//Facet" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Facets allow to enrich an architecture element. For example, an increment might have a cost model facet describing different types of cost associated with the increment."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass ../../org.nasdanika.ncore/model/ncore.ecore#//Property"
        containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//Property/name">
      <eAnnotations source="urn:org.nasdanika">
        <details key="reference-type" value="map: &#xA;  ns-uri: urn:org.nasdanika.ncore&#xA;  name: MapProperty&#xA;list: &#xA;  ns-uri: urn:org.nasdanika.ncore&#xA;  name: ListProperty&#xA;string: &#xA;  ns-uri: urn:org.nasdanika.ncore&#xA;  name: StringProperty&#xA;integer: &#xA;  ns-uri: urn:org.nasdanika.ncore&#xA;  name: IntegerProperty"/>
        <details key="value-feature" value="value"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Architecture element properties"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="#//ArchitectureElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Domain is a grouping construct for architecture elements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ArchitectureElement" containment="true" eKeys="#//ModelElement/id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Increment" eSuperTypes="#//ArchitectureElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A transition of the containing architecture element from the baseline state identified by the increment start to the target state identified by the increment end."/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
