<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kubernetes" nsURI="ecore://nasdanika.org/architecture/containers/kubernetes"
    nsPrefix="org.nasdanika.architecture.containers.kubernetes">
  <eAnnotations source="urn:org.nasdanika">
    <details key="documentation-reference" value="doc/package-summary.md"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Cluster" eSuperTypes="../../org.nasdanika.architecture.core/model/core.ecore#//ArchitectureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pod"/>
  <eClassifiers xsi:type="ecore:EClass" name="Workload">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="https://kubernetes.io/docs/concepts/workloads/"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
