<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="c4" nsURI="urn:org.nasdanika.architecture.c4" nsPrefix="org.nasdanika.architecture.c4">
  <eAnnotations source="urn:org.nasdanika">
    <details key="documentation-reference" value="doc/package-summary.md"/>
    <details key="load-key" value="c4"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Technology" eSuperTypes="../../org.nasdanika.architecture.core/model/core.ecore#//ArchitectureElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A class representing some technology. E.g. a software product or its version."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" upperBound="-1" eType="#//TechnologyConsumer"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Uses of this technology - computed opposite to TechnologyConsumer.technology"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TechnologyProduct" eSuperTypes="#//Technology">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Technology product. For example, a software product like Java, or a standard like TOGAF or HTML."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" upperBound="-1"
        eType="#//TechnologyVersion" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TechnologyVersion" eSuperTypes="#//Technology">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Version of a technology product. E.g. Java 17, TOGAF 10, or HTML 5."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TechnologyConsumer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for classes which leverage technologies, e.g. a container or a component."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="technology" upperBound="-1"
        eType="#//Technology">
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="uses"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Technologies used by this element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="../../org.nasdanika.architecture.core/model/core.ecore#//Relationship #//TechnologyConsumer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A relationship between two nodes. Relationships are contained by their source nodes and reference their targets using the target reference."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="../../org.nasdanika.architecture.core/model/core.ecore#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A person represents one of the human users of your software system (e.g. actors, roles, personas, etc)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="external" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If true, the person is external to the system described by the architecture. In other words it is not part of the system, but belongs to the system context/surroundings."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="../../org.nasdanika.architecture.core/model/core.ecore#//Node ../../org.nasdanika.architecture.core/model/core.ecore#//Domain">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A software system is the highest level of abstraction and describes something that delivers value to its users, whether they are human or not. This includes the software system you are modelling, and the other software systems upon which your software system depends (or vice versa). Systems extends Domain to support adding reference data, e.g. technology stack."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="external" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If true, the system is external to the system (landscape) described by the architecture. In other words it is not part of the system (landscape), but belongs to the system context/surroundings."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//Container" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Containers consituting the system."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsystems" upperBound="-1"
        eType="#//System" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Subsystem is a logical grouping of related containers and subsystems."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="../../org.nasdanika.architecture.core/model/core.ecore#//Node #//TechnologyConsumer">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/container.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Components consituting the container."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Container" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Containers can be nested. E.g. Tomcat may be running in a Docker container and serve multiple applications."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//Module">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/component.md"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="../../org.nasdanika.architecture.core/model/core.ecore#//Node #//TechnologyConsumer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Module is an implementation unit. E.g. a Java jar file/module. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeElements" upperBound="-1"
        eType="#//CodeElement" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A component/module contains code elements."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Modules can be nested. E.g. a Maven module may contain sub-modules. A Java package may be considered a module."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeElement" eSuperTypes="../../org.nasdanika.architecture.core/model/core.ecore#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Classes, interfaces, objects, functions, database tables, etc"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
