<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="storage" nsURI="ecore://nasdanika.org/architecture/cloud/azure/storage"
    nsPrefix="org.nasdanika.architecture.cloud.azure.storage">
  <eAnnotations source="urn:org.nasdanika">
    <details key="documentation-reference" value="doc/package-summary.md"/>
    <details key="load-key" value="azure-storage"/>
    <details key="exports" value="StorageAccount: azure-storage-account"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="StorageAccount" eSuperTypes="../../org.nasdanika.architecture.cloud.azure.core/model/core.ecore#//Resource">
    <eAnnotations source="urn:org.nasdanika">
      <details key="icon" value="https://cdn.jsdelivr.net/gh/Nasdanika/architecture@main/cloud/azure/icons/svg/Icons/storage/10086-icon-service-Storage-Accounts.svg"/>
      <details key="label" value="Storage Account"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlobStorage" eSuperTypes="../../org.nasdanika.architecture.cloud.azure.core/model/core.ecore#//AzureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataLakeStorageGen2" eSuperTypes="../../org.nasdanika.architecture.cloud.azure.core/model/core.ecore#//AzureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AzureFiles" eSuperTypes="../../org.nasdanika.architecture.cloud.azure.core/model/core.ecore#//AzureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="QueueStorage" eSuperTypes="../../org.nasdanika.architecture.cloud.azure.core/model/core.ecore#//AzureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableStorage" eSuperTypes="../../org.nasdanika.architecture.cloud.azure.core/model/core.ecore#//AzureElement"/>
</ecore:EPackage>
